
development:
  url: {{envOr "DEVELOP_DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/practice_test?sslmode=disable"}}

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/practice_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/practice_production?sslmode=disable"}}
